name = "wheelofdeath"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "WHEELS"
id = "a9448683d6dd40f0b80cb36963b009e1"
